language: go
install: make get-deps
go:
- tip
before_deploy: "make release"
deploy:
  provider: releases
  api_key:
    secure: WNXZXK2itJHhBL+YUXFl4QykFX17k9KvsXVbl2yi9J6uFbLsGxAcsK6awXPmcs2vkfxsJzoLMRno2AFHihIIHjweOzMBGb5dKGdvQ4Yv//LyvR8ts/Bp2x2jprD7L17PdApOIGAN11/3viSOYXfIdd6Bd9zsN1COKuJGWRkNYzJcdlbnq83n0xVWf2rX70NqwohkqZLT81DnxbELFnQGjqRsdW+lSDkSxHOFalglBD5nct6/G+xLj0DoC/3zOuP9pOckSjmXL/5Heb2RPzenkCMzrsa1d4qToxInVOS/8XNd5YsozFWLp7BtnzEdHHbPqdfpRJiKg//W6LC6VgEniNgWaklMzz0Bccq3VAC/Kp/xlmrbcu53pNXPGfUrMvnqfPhSPornAsEHwYNlAB1OCpIRh0l1SZxxOE0zh9wLA9RgCXVdesCcTPPh5qw/ipTeThKyjbYejLS6fPoDUldb8bU+TnyASt+G+Gw6fxfK8zqLgqBuYR4J4lniAYxbITyLzAkshE9OnJoboxH4qDNqCLcMyC3NdtImc4zbKQcQu+QNJ7RUecUhCMnynnsf+JeMU3XcYWCZImT/V/qrl6yXXQAg+uet5DKX/9wPSH24N2LRcZH02efcNNEMETo+XNTTU12Qrpdv9d7b6nOmgth2/v/xaWf0l8hdhTYld2cz/F8=
  file:
     - "simplepush-linux-amd64"
     - "simplepush-darwin-amd64"
     - "simplepush-openbsd-amd64"
     - "simplepush-windows-amd64"
     - "simplepush-alpine-amd64"
  skip_cleanup: true
  on:
     tags: true
